### ISSUE TITLE
Add on Uworld not working

### ISSUE THREAD

**Issue by Colonfabiola5** [AnKing-VIP/ankiweb-placeholder#121]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Placeholder - UWqidAS - DOES NOT WORK read instructions:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Fabiola\AppData\Roaming\Anki2\addons21\607963104\__init__.py", line 1, in <module>
    from .gui.menu import setup_menu
  File "C:\Users\Fabiola\AppData\Roaming\Anki2\addons21\607963104\gui\__init__.py", line 1, in <module>
    from .resources.anki21 import icons_rc  # type: ignore # noqa: F401
  File "C:\Users\Fabiola\AppData\Roaming\Anki2\addons21\607963104\gui\resources\anki21\__init__.py", line 20, in <module>
    from . import icons_rc
  File "C:\Users\Fabiola\AppData\Roaming\Anki2\addons21\607963104\gui\resources\anki21\icons_rc.py", line 9, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'

**Comment by AnKingMed** [comment]
You have the placeholder. Delete that addon and download the actual file from the vip dashboard www.theanking.com/vip
