### ISSUE TITLE
AnkiHub Error

### ISSUE THREAD

**Issue by ih8notstudying** [AnKing-VIP/ankiweb-placeholder#93]
## Which add-on is this about?
AnkiHub

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

- Downloaded Ankihub and it says it's not working due to an addon. 
- Tried opening with shift held down, no problem with anki itself, but when opened again, doesn't work. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.12.1
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.2-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 496, in loadProfile
  File "_aqt.hooks", line 4101, in __call__
  File "/Users/ctheisen/Library/Application Support/Anki2/addons21/1322529746/entry_point.py", line 55, in _on_profile_did_open
    if not _profile_setup():
  File "/Users/ctheisen/Library/Application Support/Anki2/addons21/1322529746/entry_point.py", line 76, in _profile_setup
    if not setup_profile_data_folder():
  File "/Users/ctheisen/Library/Application Support/Anki2/addons21/1322529746/settings.py", line 416, in setup_profile_data_folder
    if not _maybe_migrate_profile_data_from_old_location():
  File "/Users/ctheisen/Library/Application Support/Anki2/addons21/1322529746/settings.py", line 489, in _maybe_migrate_profile_data_from_old_location
    if not _profile_data_exists_at_old_location():
  File "/Users/ctheisen/Library/Application Support/Anki2/addons21/1322529746/settings.py", line 480, in _profile_data_exists_at_old_location
    result = (user_files_path() / PRIVATE_CONFIG_FILENAME).exists()
  File "pathlib", line 1424, in exists
  File "pathlib", line 1232, in stat
PermissionError: [Errno 13] Permission denied: '/Users/ctheisen/Library/Application Support/Anki2/addons21/1322529746/user_files/.private_config.json'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T11:01, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-01-19T15:17, 'None', mod]
AnkiHub ['1322529746', 2024-02-29T07:26, 'None', '']
BetterSearch ['1052724801', 2024-03-03T13:52, 'None', '']
Clickable Tags v20 original ['380714095', 2022-01-30T16:58, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T20:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T04:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T01:19, '6.18', mod]
Hint Hotkeys ['1844908621', 2023-04-14T09:13, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
Postpone cards review ['1152543397', 2023-04-14T21:29, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
Special Fields ['1102281552', 2023-11-01T11:37, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T05:24, 'None', '']
uworld_qid_to_anki_search ['607963104', 2023-09-21T10:18, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 1052724801 1102281552 1152543397 1210908941 1322529746 1374772155 1771074083 1844908621 24411424 380714095 385888438 607963104 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by AnKingMed** [comment]
Please report AnkiHub issues on community.AnkiHub.net
