### ISSUE TITLE
WH placeholder will not start up

### ISSUE THREAD

**Issue by pattyb69** [AnKing-VIP/ankiweb-placeholder#98]
## Which add-on is this about?
WH addon placeholder

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
Signed up for anking vip and paid, wh addon will not start, everything else works great

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨24.04 (429bc9e1)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
[Visit website](https://apps.ankiweb.net/)
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Placeholder - WH:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\1992008104\__init__.py", line 1, in <module>
    from .gui.menu import setup_menu
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\1992008104\gui\__init__.py", line 1, in <module>
    from .resources.anki21 import icons_rc  # type: ignore # noqa: F401
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\1992008104\gui\resources\anki21\__init__.py", line 20, in <module>
    from . import icons_rc
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\1992008104\gui\resources\anki21\icons_rc.py", line 9, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'

When loading Placeholder - UWqidAS - DOES NOT WORK read instructions:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\607963104\__init__.py", line 1, in <module>
    from .gui.menu import setup_menu
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\607963104\gui\__init__.py", line 1, in <module>
    from .resources.anki21 import icons_rc  # type: ignore # noqa: F401
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\607963104\gui\resources\anki21\__init__.py", line 20, in <module>
    from . import icons_rc
  File "C:\Users\OWNER\AppData\Roaming\Anki2\addons21\607963104\gui\resources\anki21\icons_rc.py", line 9, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'



```

**Comment by AnKingMed** [comment]
That addon is just a placeholder. The actual addon can be downloaded from the VIP dashboard

www.theanking.com/vip
